sudo: false
language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - ruby-head
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
